### ISSUE TITLE
Better indication of app action progress, particularly for the initial creates and push/pull

### ISSUE THREAD

**Issue by bitbrained** [kalabox/kalabox#1165]
While creating a Pantheon app by invoking `kbox create pantheon`, the progress indicator for downloading the tar archive for `kalabox/kalabox-app-pantheon` shows `NaN%`.

Sample:
```
Creating.
Cleaning up.
Running pre create tasks.
Creating app structure.
Downloading: [NaN%] ...box-app-pantheon/tarball/v0.12.0-alpha.7
```

Output for `kbox version` is `0.12.0-alpha.18`

**Comment by pirog** [comment]
I think this is just a problem with the output. Shouldn't reflect an actual issue.

That said we should have better output.

**Comment by bitbrained** [comment]
@pirog, yes, confirming that it's just a display issue. The assets are still downloaded correctly.

**Comment by jsArgus** [comment]
Same goes for the UI, a progress bar or something like that when downloading a site would be great.

**Comment by pirog** [comment]
So we want to do two main things here

- [ ] Switch the throbber to include some sort of progress indicator. 
- [ ] Increment progress by a reasonable/small amount when app receives a status message
- [ ] We need to attach the status class to the app object and use that
- [ ] Figure out how to handle stdout trolling re: app specificity 
- [ ] Display a truncated status message with a tooltip that contains the entire message
