### ISSUE TITLE
QA Multiapp and create bug fix issues

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1202]

**Comment by pirog** [comment]
@reynoldsalec @rileysaurus 

created an epic to post all our multiapp bug fix issues here

**Comment by pirog** [comment]
Here are some obvious things to consider

- [ ] `kbox create`s don't show up immediately. Sidebar remains. App shows up once `appserver` is created
- [ ] `kbox pull/push` errors with `sitename not found`
- [ ] `kbox destroy`s seem to block other things, (saw an error with appRegistry.lock`)
- [ ] Should we improve how `kbox start/stop`s work re: #1160
