### ISSUE TITLE
Make sure we can add custom drush commandfiles/config and that the process for doing this is documented

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1298]
Feature/Enhancement Request
===========================

I am a user who needs to add additional drush config to my kalabox project. This could include aliases, commandfiles or config. I need an easy and reliable way to do this and i need good documentation to make the process as clear as https://www.youtube.com/watch?v=KmKOVdAGtzM

#### Tasks

- [x] Verify that we can easily add custom drush files into our apps (both stock and pantheon) 
- [x] Provide this functionality if needed
- [ ] ~~Document this process for all the people~~

#### **NOTES:**

I *think* you can already add custom drush commands (to pantheon apps at least). Here is a starter for some docs around that

1. Go to `config/drush` from your app root
2. Extract relevant commandfiles, aliases, etc into this directory
3. Run your `kbox drush` command

**Comment by pirog** [comment]
PANTHEON PR: https://github.com/kalabox/kalabox-app-pantheon/pull/142
