### ISSUE TITLE
Reboot all the docs

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox#1322]
Feature/Enhancement Request
===========================

As a user or developer i need a one-stop-shop for all my documentation needs. This would include:

- [x] A central place for all documentation
- [x] Routes to this from outside "documentation" ie github readmes
- [x] A nice organization for the docs (see below)

#### High level concerns

1. General info
2. App specific
3. 

#### Proposed documentation outline

Freshdesk
```
1. Getting Started
 - System requirements
 - Installing Kalabox (Combine current docs)
 - Using Kalabox (basic overview of GUI/CLI/Commands)
 - Architecture of Kalabox and Apps (Go through full stack from installer to app with linked terms)
 - Uninstall Kalabox
2. Apps
 - Quickstarts for each app (more or less whats in the github readme already)
3. Customizing Kalabox
 - Extending services and tools
 - Overriding config
 - Custom plugins and apps
 - Docs on how to share custom kalabox repos
 - How to deal with non-standard Drupal code roots (symlink issues with Drush Make, multi-site, Drupal in subdirectory of the web root IE Acquia config)
4. Troubleshooting (FAQ)
- How to setup email logging in Drupal (replacement for Mailhog while we don't have Pro)
5. Contributing -> link to github
```

Github readme structure
````
Brief intro / purpose
Header of each freshdesk item and then list of links
Contributing guide
more info
````

#### Tasks

- [ ] Refactor all github READMEs to reflect above style @pirog
- [x] Refactor "Getting started section" into the above @reynoldsalec 
- [ ] Add in app specific quickstarts @pirog
- [x] Refactor FAQ to troubleshooting @reynoldsalec 
- [ ] Refactor the Customizing and Contrib guides @pirog
- [ ] Update the freshdesk stylinz @reynoldsalec 

### Other doc considerations

- [ ] #1141 
- [ ] #1266 (and its ilk)
